version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "passs"
      MYSQL_DATABASE: "db_name"
      MYSQL_USER: "usser"
      MYSQL_PASSWORD: "passs"
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nextjs-destination-chooser:
    build: .
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://usser:passs@mysql:3306/db_name"
    ports:
      - 3000:3000
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge