version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_database_name
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nextjs-destination-chooser:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://your_postgres_username:your_postgres_password@postgres:5432/your_postgres_database_name
    ports:
      - 3000:3000

volumes:
  postgres-data:
